name       : menu-cache
version    : 1.1.0
release    : 2
source     :
    - git|https://github.com/lxde/menu-cache.git : 1.1.0
license    : LGPL-2.1
component  : programming.library
summary    : Library used to read freedesktop.org menus.
description: |
    Library used to read freedesktop.org menus.
builddeps  :
    - gtk-doc
    - pkgconfig(glib-2.0)
    - pkgconfig(libfm-extra)
setup      : |
    %autogen
build      : |
    %make
install    : |
    %make_install
