name       : lxqt-sudo
version    : 0.14.0
release    : 3
source     :
    - git|https://github.com/lxde/lxqt-sudo.git : 0.14.0
license    : LGPL-2.1
component  : desktop.lxqt.core
summary    : GUI frontend for sudo/su.
description: |
    A graphical front-end of commands sudo and su respectively. As such it enables regular users to launch applications with permissions of other users including root.
builddeps  :
    - kwindowsystem-devel
    - lxqt-build-tools-devel
    - pkgconfig(gl)
    - pkgconfig(lxqt)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5Widgets)
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
