name       : lxqt-sudo
version    : 0.12.0
release    : 1
source     :
    - https://github.com/lxde/lxqt-sudo/archive/0.12.0.tar.gz : d3cadcc7cb28d38b79e0f36320b18b91564a8da132ddfa3bd6fd112439e7653a
license    : LGPL-2.1
component  : desktop.lxqt.core
summary    : GUI frontend for sudo/su.
description: |
    A graphical front-end of commands sudo and su respectively. As such it enables regular users to launch applications with permissions of other users including root.
builddeps  :
    - kwindowsystem-devel
    - lxqt-build-tools-devel
    - pkgconfig(gl)
    - pkgconfig(lxqt)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5Widgets)
setup      : |
    mkdir build
    pushd build
    %cmake -DPULL_TRANSLATIONS=false ..
    popd
build      : |
    pushd build
    %make
    popd
install    : |
    pushd build
    %make_install
    popd
