name       : pcmanfm-qt
version    : 0.14.0
release    : 4
source     :
    - git|https://github.com/lxde/pcmanfm-qt.git : 0.14.0
license    : GPL-2.0
component  : desktop.lxqt.core
summary    : File manager and desktop icon manager (Qt port of PCManFM and libfm)
description: |
    PCManFM-Qt is the Qt port of PCManFM, the file manager of LXDE.
builddeps  :
    - lxqt-build-tools-devel
    - pkgconfig(gl)
    - pkgconfig(libexif)
    - pkgconfig(libfm)
    - pkgconfig(libfm-qt)
    - pkgconfig(libmenu-cache)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5Widgets)
    - pkgconfig(Qt5X11Extras)
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
