name       : libfm-extra
version    : 1.3.1
release    : 3
source     :
    - git|https://github.com/lxde/libfm.git : 1.3.1
license    : GPL-2.0
component  : desktop.lxqt.core
summary    : Core library of PCManFM file manager
description: |
    Core library of PCManFM file manager
builddeps  :
    - gtk-doc
setup      : |
    %autogen --with-extra-only --with-gtk=no
build      : |
    %make
install    : |
    %make_install
