name       : lxqt-l10n
version    : 0.12.0
release    : 1
source     :
    - https://github.com/lxde/lxqt-l10n/archive/0.12.0.tar.gz : 5ed02b6421168c8e566b4b2235c3ce9592b2d83deeda70c9db897f611a85fea3
license    : LGPL-2.1
component  : desktop.lxqt.core
summary    : Translations of LXQt.
description: |
    Translations of LXQt.
builddeps  :
    - lxqt-build-tools-devel
    - pkgconfig(Qt5UiTools)
setup      : |
    mkdir build
    pushd build
    %cmake ..
    popd
build      : |
    pushd build
    %make
    popd
install    : |
    pushd build
    %make_install
    popd
