name       : lxqt-panel
version    : 0.14.0
release    : 3
source     :
    - git|https://github.com/lxde/lxqt-panel.git : 0.14.0
license    : LGPL-2.1
component  : desktop.lxqt.core
summary    : The LXQt desktop panel.
description: |
     The taskbar of LXQt.
builddeps  :
    - kwindowsystem-devel
    - lm_sensors-devel
    - lxqt-build-tools-devel
    - pkgconfig(alsa)
    - pkgconfig(dbusmenu-qt5)
    - pkgconfig(gl)
    - pkgconfig(libpulse)
    - pkgconfig(libstatgrab)
    - pkgconfig(lxqt)
    - pkgconfig(lxqt-globalkeys)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5Widgets)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(sysstat-qt5)
    - pkgconfig(xcb-util)
    - pkgconfig(xcomposite)
    - pkgconfig(xkbcommon)
    - pkgconfig(xkbcommon-x11)
    - pkgconfig(xrender)
    - solid-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
