name       : lxqt-panel
version    : 0.12.0
release    : 1
source     :
    - https://github.com/lxde/lxqt-panel/archive/0.12.0.tar.gz : 2d495c019dce44d523ebca5d01d7b0409ff5e261b86090c4baaefc9d3fbaecc2
license    : LGPL-2.1
component  : desktop.lxqt.core
summary    : The LXQt desktop panel.
description: |
     The taskbar of LXQt.
builddeps  :
    - kwindowsystem-devel
    - lm_sensors-devel
    - lxqt-build-tools-devel
    - pkgconfig(alsa)
    - pkgconfig(dbusmenu-qt5)
    - pkgconfig(gl)
    - pkgconfig(libpulse)
    - pkgconfig(libstatgrab)
    - pkgconfig(lxqt)
    - pkgconfig(lxqt-globalkeys)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5Widgets)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(sysstat-qt5)
    - pkgconfig(xcb-util)
    - pkgconfig(xcomposite)
    - pkgconfig(xkbcommon)
    - pkgconfig(xkbcommon-x11)
    - pkgconfig(xrender)
    - solid-devel
setup      : |
    mkdir build
    pushd build
    %cmake -DPULL_TRANSLATIONS=false ..
    popd
build      : |
    pushd build
    %make
    popd
install    : |
    pushd build
    %make_install
    popd
