name       : libqtxdg
version    : 3.3.0
release    : 3
source     :
    - git|https://github.com/lxde/libqtxdg.git : 3.3.0
license    : LGPL-2.1
component  : desktop.qt
summary    : Qt implementation of freedesktop.org xdg specs.
description: |
    Qt implementation of freedesktop.org xdg specs, maintained by the LXQt project, with nearly all LXQt components depending on it.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - pkgconfig(Qt5Svg)
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
