name       : libqtxdg
version    : 3.2.0
release    : 2
source     :
    - git|https://github.com/lxde/libqtxdg.git : 3.2.0
license    : LGPL-2.1
component  : desktop.qt
summary    : Qt implementation of freedesktop.org xdg specs.
description: |
    Qt implementation of freedesktop.org xdg specs, maintained by the LXQt project, with nearly all LXQt components depending on it.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - pkgconfig(Qt5Svg)
setup      : |
    mkdir build
    pushd build
    %cmake ..
    popd
build      : |
    pushd build
    %make
    popd
install    : |
    pushd build
    %make_install
    popd
