name       : libqtxdg
version    : 3.1.0
release    : 1
source     :
    - https://github.com/lxde/libqtxdg/archive/3.1.0.tar.gz : 0bf3f35c8cac3ab332872a2bb0e453ab02849944d02b5cda1c6f2cd7df5f9a36
license    : LGPL-2.1
component  : desktop.qt
summary    : Qt implementation of freedesktop.org xdg specs.
description: |
    Qt implementation of freedesktop.org xdg specs, maintained by the LXQt project, with nearly all LXQt components depending on it.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - pkgconfig(Qt5Svg)
setup      : |
    mkdir build
    pushd build
    %cmake ..
    popd
build      : |
    pushd build
    %make
    popd
install    : |
    pushd build
    %make_install
    popd
