name       : libfm
version    : 1.3.0.2
release    : 2
source     :
    - git|https://github.com/lxde/libfm.git : 1.3.0.2
license    : GPL-2.0
component  : desktop.lxqt.core
summary    : Core library of PCManFM file manager
description: |
    Core library of PCManFM file manager
builddeps  :
    - gtk-doc
    - pkgconfig(cairo)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(libexif)
    - pkgconfig(libmenu-cache)
    - pkgconfig(pango)
    - vala
setup      : |
    %autogen
build      : |
    %make
install    : |
    %make_install
    rm "${installdir}/%libdir%/libfm-extra"*
