name       : lxqt-admin
version    : 0.13.0
release    : 2
source     :
    - git|https://github.com/lxde/lxqt-admin.git : 0.13.0
license    : LGPL-2.1
component  : desktop.lxqt.core
summary    : LXQt system administration tool.
description: |
    LXQt system administration tool
builddeps  :
    - kwindowsystem-devel
    - lxqt-build-tools-devel
    - pkgconfig(gl)
    - pkgconfig(lxqt)
    - pkgconfig(polkit-qt5-1)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5Widgets)
setup      : |
    mkdir build
    pushd build
    %cmake -DPULL_TRANSLATIONS=false ..
    popd
build      : |
    pushd build
    %make
    popd
install    : |
    pushd build
    %make_install
    popd
