name       : lxqt-about
version    : 0.13.0
release    : 2
source     :
    - git|https://github.com/lxde/lxqt-about.git : 0.13.0
license    : LGPL-2.1
component  : desktop.lxqt.core
summary    : Dialogue window providing information about LXQt and the system it's running on.
description: |
    Dialogue window providing information about LXQt and the system it's running on.
builddeps  :
    - kwindowsystem-devel
    - lxqt-build-tools-devel
    - pkgconfig(gl)
    - pkgconfig(lxqt)
    - pkgconfig(Qt5UiTools)
setup      : |
    mkdir build
    pushd build
    %cmake -DPULL_TRANSLATIONS=false ..
    popd
build      : |
    pushd build
    %make
    popd
install    : |
    pushd build
    %make_install
    popd
