name       : lxqt-qtplugin
version    : 0.14.0
release    : 4
source     :
    - git|https://github.com/lxde/lxqt-qtplugin.git : 0.14.0
license    : LGPL-2.1
component  : desktop.lxqt.core
summary    : LXQt Qt platform integration plugin.
description: |
    With this plugin, all Qt-based programs can adopt settings of LXQt, such as the icon theme.
builddeps  :
    - kwindowsystem-devel
    - lxqt-build-tools-devel
    - pkgconfig(dbusmenu-qt5)
    - pkgconfig(gl)
    - pkgconfig(libexif)
    - pkgconfig(libfm-qt)
    - pkgconfig(libmenu-cache)
    - pkgconfig(lxqt)
    - pkgconfig(Qt5DBus)
    - pkgconfig(Qt5UiTools)
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
