name       : lxqt-notificationd
version    : 0.14.0
release    : 3
source     :
    - git|https://github.com/lxde/lxqt-notificationd.git : 0.14.0
license    : LGPL-2.1
component  : desktop.lxqt.core
summary    : The LXQt notification daemon.
description: |
    LXQt's implementation of a daemon according to the Desktop Notifications Specification.
builddeps  :
    - kwindowsystem-devel
    - lxqt-build-tools-devel
    - pkgconfig(gl)
    - pkgconfig(lxqt)
    - pkgconfig(Qt5DBus)
    - pkgconfig(Qt5UiTools)
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
