name       : libsysstat
version    : 0.4.1
release    : 2
source     :
    - git|https://github.com/lxde/libsysstat.git : 0.4.1
license    : LGPL-2.1
component  : system.utils
summary    : Library used to query system info and statistics.
description: |
    Library used to query system information like CPU and memory usage or network traffic. Conceptually, it is roughly similar to libstatgrab.
builddeps  :
    - lxqt-build-tools-devel
    - pkgconfig(Qt5Core)
setup      : |
    mkdir build
    pushd build
    %cmake ..
    popd
build      : |
    pushd build
    %make
    popd
install    : |
    pushd build
    %make_install
    popd
