name       : libfm-qt
version    : 0.13.0
release    : 2
source     :
    - git|https://github.com/lxde/libfm-qt.git : 0.13.0
license    : LGPL-2.1
component  : desktop.lxqt.core
summary    : Core library of PCManFM-Qt (Qt binding for libfm).
description: |
    libfm-qt is the Qt port of libfm, a library providing components to build desktop file managers which belongs to LXDE.
builddeps  :
    - lxqt-build-tools-devel
    - pkgconfig(libexif)
    - pkgconfig(gl)
    - pkgconfig(libfm)
    - pkgconfig(libmenu-cache)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5Widgets)
    - pkgconfig(Qt5X11Extras)
setup      : |
    mkdir build
    pushd build
    %cmake -DPULL_TRANSLATIONS=false ..
    popd
build      : |
    pushd build
    %make
    popd
install    : |
    pushd build
    %make_install
    popd
