name       : lxqt-config
version    : 0.14.0
release    : 3
source     :
    - git|https://github.com/lxde/lxqt-config.git : 0.14.0
license    : LGPL-2.1
component  : desktop.lxqt.core
summary    : Tools to configure LXQt and the underlying operating system.
description: |
    Tools to configure LXQt and the underlying operating system.
builddeps  :
    - kwindowsystem-devel
    - lxqt-build-tools-devel
    - pkgconfig(gl)
    - pkgconfig(kscreen2)
    - pkgconfig(xorg-libinput)
    - pkgconfig(lxqt)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5Widgets)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xcursor)
    - pkgconfig(xi)
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
