name       : obconf-qt
version    : 0.14.0
release    : 3
source     :
    - git|https://github.com/lxde/obconf-qt.git : 0.14.0
license    : GPL-2.0
component  : desktop.lxqt.core
summary    : The Qt port of obconf.
description: |
    The Qt port of obconf, a configuration editor for window manager OpenBox.
builddeps  :
    - kwindowsystem-devel
    - lxqt-build-tools-devel
    - pkgconfig(gl)
    - pkgconfig(lxqt)
    - pkgconfig(obrender-3.5)
    - pkgconfig(obt-3.5)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5Widgets)
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
