name       : lxqt-runner
version    : 0.14.0
release    : 3
source     :
    - git|https://github.com/lxde/lxqt-runner.git : 0.14.0
license    : LGPL-2.1
component  : desktop.lxqt.core
summary    : Tool used to launch programs quickly by typing their names.
description: |
    Provides a GUI that comes up on the desktop and allows for launching applications or shutting down the system.
builddeps  :
    - kwindowsystem-devel
    - lxqt-build-tools-devel
    - pkgconfig(gl)
    - pkgconfig(libmenu-cache)
    - pkgconfig(lxqt)
    - pkgconfig(lxqt-globalkeys)
    - pkgconfig(muparser)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5Widgets)
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
