name       : lxqt-runner
version    : 0.13.0
release    : 2
source     :
    - git|https://github.com/lxde/lxqt-runner.git : 0.13.0
license    : LGPL-2.1
component  : desktop.lxqt.core
summary    : Tool used to launch programs quickly by typing their names.
description: |
    Provides a GUI that comes up on the desktop and allows for launching applications or shutting down the system.
builddeps  :
    - kwindowsystem-devel
    - lxqt-build-tools-devel
    - pkgconfig(gl)
    - pkgconfig(libmenu-cache)
    - pkgconfig(lxqt)
    - pkgconfig(lxqt-globalkeys)
    - pkgconfig(muparser)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5Widgets)
setup      : |
    mkdir build
    pushd build
    %cmake -DPULL_TRANSLATIONS=false ..
    popd
build      : |
    pushd build
    %make
    popd
install    : |
    pushd build
    %make_install
    popd
