name       : liblxqt
version    : 0.14.0
release    : 3
source     :
    - git|https://github.com/lxde/liblxqt.git : 0.14.0
license    : LGPL-2.1
component  : desktop.lxqt.core
summary    : Core utility library for all LXQt components.
description: |
    Core library of LXQt providing essential functionality needed by nearly all of its components.
builddeps  :
    - kwindowsystem-devel
    - lxqt-build-tools-devel
    - pkgconfig(gl)
    - pkgconfig(polkit-qt5-1)
    - pkgconfig(Qt5Core)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(Qt5Xdg)
    - pkgconfig(x11)
    - pkgconfig(xscrnsaver)
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
