name       : liblxqt
version    : 0.13.0
release    : 2
source     :
    - git|https://github.com/lxde/liblxqt.git : 0.13.0
license    : LGPL-2.1
component  : desktop.lxqt.core
summary    : Core utility library for all LXQt components.
description: |
    Core library of LXQt providing essential functionality needed by nearly all of its components.
builddeps  :
    - kwindowsystem-devel
    - lxqt-build-tools-devel
    - lxqt-l10n
    - pkgconfig(gl)
    - pkgconfig(polkit-qt5-1)
    - pkgconfig(Qt5Core)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(Qt5Xdg)
    - pkgconfig(x11)
    - pkgconfig(xscrnsaver)
setup      : |
    mkdir build
    pushd build
    %cmake -DPULL_TRANSLATIONS=false ..
    popd
build      : |
    pushd build
    %make
    popd
install    : |
    pushd build
    %make_install
    popd
