name       : lxqt-themes
version    : 0.14.0
release    : 3
source     :
    - git|https://github.com/lxde/lxqt-themes.git : 0.14.0
license    : LGPL-2.1
component  : desktop.lxqt
summary    : Themes, graphics and icons for LXQt.
description: |
    Themes, graphics and icons for LXQt
builddeps  :
    - lxqt-build-tools-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
