name       : lxqt-themes
version    : 0.13.0
release    : 2
source     :
    - git|https://github.com/lxde/lxqt-themes.git : 0.13.0
license    : LGPL-2.1
component  : desktop.lxqt
summary    : Themes, graphics and icons for LXQt.
description: |
    Themes, graphics and icons for LXQt
builddeps  :
    - lxqt-build-tools-devel
setup      : |
    mkdir build
    pushd build
    %cmake -DPULL_TRANSLATIONS=false ..
    popd
build      : |
    pushd build
    %make
    popd
install    : |
    pushd build
    %make_install
    popd
