name       : lxqt-themes
version    : 0.12.0
release    : 1
source     :
    - https://github.com/lxde/lxqt-themes/archive/0.12.0.tar.gz : 0e5d62ccb21debd991e165af24105cc7b8836243d7f2f35188e29e31784d5e42
license    : LGPL-2.1
component  : desktop.lxqt
summary    : Themes, graphics and icons for LXQt.
description: |
    Themes, graphics and icons for LXQt
builddeps  :
    - lxqt-build-tools-devel
setup      : |
    mkdir build
    pushd build
    %cmake -DPULL_TRANSLATIONS=false ..
    popd
build      : |
    pushd build
    %make
    popd
install    : |
    pushd build
    %make_install
    popd
