name       : lxqt-policykit
version    : 0.13.0
release    : 2
source     :
    - git|https://github.com/lxde/lxqt-policykit.git : 0.13.0
license    : LGPL-2.1
component  : desktop.lxqt.core
summary    : The LXQt PolicyKit agent.
description: |
    The polkit authentification agent of LXQt.
builddeps  :
    - kwindowsystem-devel
    - lxqt-build-tools-devel
    - pkgconfig(gl)
    - pkgconfig(lxqt)
    - pkgconfig(polkit-qt5-1)
    - pkgconfig(Qt5DBus)
    - pkgconfig(Qt5UiTools)
setup      : |
    mkdir build
    pushd build
    %cmake -DPULL_TRANSLATIONS=false ..
    popd
build      : |
    pushd build
    %make
    popd
install    : |
    pushd build
    %make_install
    popd
