name       : lxqt-session
version    : 0.12.0
release    : 1
source     :
    - https://github.com/lxde/lxqt-session/archive/0.12.0.tar.gz : 7f15a7386ab5141f02ffeb3a977697aef02314d25ad7886ddbad3f22be396dbe
license    : LGPL-2.1
component  : desktop.lxqt.core
summary    : The LXQt session manager.
description: |
    Provides tools to handle LXQt sessions.
builddeps  :
    - kwindowsystem-devel
    - lxqt-build-tools-devel
    - pkgconfig(gl)
    - pkgconfig(lxqt)
    - pkgconfig(Qt5DBus)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(x11)
    - xdg-user-dirs
rundeps    :
    - lxqt-about
    - lxqt-admin
    - lxqt-config
    - lxqt-globalkeys
    - lxqt-l10n
    - lxqt-notificationd
    - lxqt-openssh-askpass
    - lxqt-panel
    - lxqt-policykit
    - lxqt-powermanagement
    - lxqt-qtplugin
    - lxqt-runner
    - lxqt-sudo
    - lxqt-themes
    - pcmanfm-qt
    - obconf-qt
    - openbox
setup      : |
    mkdir build
    pushd build
    %cmake -DPULL_TRANSLATIONS=false ..
    popd
build      : |
    pushd build
    %make
    popd
install    : |
    pushd build
    %make_install
    popd
