name       : lxqt-openssh-askpass
version    : 0.13.0
release    : 2
source     :
    - git|https://github.com/lxde/lxqt-openssh-askpass.git : 0.13.0
license    : LGPL-2.1
component  : desktop.lxqt.core
summary    : GUI to query passwords on behalf of SSH agents.
description: |
    lxqt-openssh-askpass is a GUI to query credentials on behalf of other programs. As indicated by its name it's primarily targeted at ssh-agent, the SSH agent of OpenSSH, but it works with other applications like e. g. EncFS as well.
builddeps  :
    - kwindowsystem-devel
    - lxqt-build-tools-devel
    - pkgconfig(gl)
    - pkgconfig(lxqt)
    - pkgconfig(Qt5DBus)
    - pkgconfig(Qt5UiTools)
setup      : |
    mkdir build
    pushd build
    %cmake -DPULL_TRANSLATIONS=false ..
    popd
build      : |
    pushd build
    %make
    popd
install    : |
    pushd build
    %make_install
    popd
