name       : lxqt-build-tools
version    : 0.4.0
release    : 1
source     :
    - https://github.com/lxde/lxqt-build-tools/archive/0.4.0.tar.gz : 2c0192aedf2a686616d29cc8f6502a9cf6d9c4c8aa7d880341029c3e898880b3
license    : BSD-3-Clause
component  : programming.tools
summary    : Various packaging tools and scripts for LXQt applications
description: |
    Several tools needed to build LXQt itself as well as other components maintained by the LXQt project.
builddeps  :
    - pkgconfig(Qt5Core)
setup      : |
    mkdir build
    pushd build
    %cmake ..
    popd
build      : |
    pushd build
    %make
    popd
install    : |
    pushd build
    %make_install
    popd
