name       : lxqt-powermanagement
version    : 0.14.0
release    : 3
source     :
    - git|https://github.com/lxde/lxqt-powermanagement.git : 0.14.0
license    : LGPL-2.1
component  : desktop.lxqt.core
summary    : Power management module for LXQt.
description: |
    Tools to monitor power management events and optionally trigger actions like e. g. shut down a system when laptop batteries are low on power.
builddeps  :
    - kidletime-devel
    - kwindowsystem-devel
    - lxqt-build-tools-devel
    - pkgconfig(gl)
    - pkgconfig(lxqt)
    - pkgconfig(Qt5DBus)
    - pkgconfig(Qt5UiTools)
    - solid-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
