name       : lxqt-powermanagement
version    : 0.13.0
release    : 2
source     :
    - git|https://github.com/lxde/lxqt-powermanagement.git : 0.13.0
license    : LGPL-2.1
component  : desktop.lxqt.core
summary    : Power management module for LXQt.
description: |
    Tools to monitor power management events and optionally trigger actions like e. g. shut down a system when laptop batteries are low on power.
builddeps  :
    - kidletime-devel
    - kwindowsystem-devel
    - lxqt-build-tools-devel
    - pkgconfig(gl)
    - pkgconfig(lxqt)
    - pkgconfig(Qt5DBus)
    - pkgconfig(Qt5UiTools)
    - solid-devel
setup      : |
    mkdir build
    pushd build
    %cmake -DPULL_TRANSLATIONS=false ..
    popd
build      : |
    pushd build
    %make
    popd
install    : |
    pushd build
    %make_install
    popd
